using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using EnvueClustering;
using EnvueClustering.ClusteringBase;
using EnvueClustering.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace EnvueClusteringAPI.Controllers
{
    /// <summary>
    /// API endpoints for controlling the clustering of streams in Envue and querying streams clusters (event streams).
    /// </summary>
    [ApiController]
    public class ClusteringController : ControllerBase
    {
        private readonly DenStream<EuclideanPoint> _denStream;
        private readonly IHostingEnvironment _env;
        private Action _terminateClusterMaintenance;
        
        public ClusteringController(IHostingEnvironment env)
        {
            _env = env;
            _denStream = new DenStream<EuclideanPoint>(
                Similarity.EuclideanDistance, 
                Similarity.EuclideanDistance);
        }

        /// <summary>
        /// Initializes the micro-cluster maintenance procedure in the density-based clustering module.
        /// Will run until the program is terminated. Can be terminated manually with the "clustering/terminate" endpoint.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("clustering/init")]
        public ActionResult InitClustering()
        {
            try
            {
                _terminateClusterMaintenance = _denStream.MaintainClusterMap();
                return Ok();
            }
            catch (Exception e)
            {
                if (_env.IsDevelopment())
                    return BadRequest(e.Message);
                return BadRequest();
            }
        }

        /// <summary>
        /// Adds a range of data objects to the data stream being clustering by the clustering module.
        /// Does not require that the micro-cluster maintenance procedure has been initialized.
        /// </summary>
        /// <param name="points"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("data/add")]
        public ActionResult AddDataPoints(IEnumerable<EuclideanPoint> points)
        {
            try
            {
                _denStream.AddToDataStream(points);
                return Ok();
            }
            catch (Exception e)
            {
                if (_env.IsDevelopment())
                    return BadRequest(e.Message);
                return BadRequest();
            }
        }

        /// <summary>
        /// Terminates the micro-cluster maintenance procedure.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("clustering/terminate")]
        public ActionResult TerminateClusterMaintenance()
        {
            try
            {
                if (_terminateClusterMaintenance == null)
                {
                    return BadRequest(
                        "Cluster maintenance has no termination handler. " +
                        "Verify that cluster maintenance has been initialized.");
                }

                _terminateClusterMaintenance?.Invoke();
                return Ok();
            }
            catch (Exception e)
            {
                if (_env.IsDevelopment())
                    return BadRequest(e.Message);
                return BadRequest();
            }
        }

        /// <summary>
        /// Returns the clusters generated by dummy data points in euclidean space (see report for the visuals).
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("test")]
        public ActionResult Test()
        {
            var filePath = $"{Directory.GetCurrentDirectory()}/Data/data.synthetic.json";
            var dataStream = ContinuousDataReader.ReadSyntheticEuclidean(filePath);

            Func<EuclideanPoint, EuclideanPoint, float> simFunc = (x, y) => 
                (float)Math.Sqrt(Math.Pow(x.X - y.X, 2) + Math.Pow(x.Y - y.Y, 2));


            Func<CoreMicroCluster<EuclideanPoint>, CoreMicroCluster<EuclideanPoint>, int, float> cmcSimFunc = (u, v, t) =>
                (float) Math.Sqrt(Math.Pow(u.Center(t).X - v.Center(t).X, 2) +
                                  Math.Pow(u.Center(t).Y - v.Center(t).Y, 2));
            
            var denStream = new DenStream<EuclideanPoint>(simFunc, cmcSimFunc);
            denStream.AddToDataStream(dataStream);
            var terminate = denStream.MaintainClusterMap();
            Thread.Sleep(5000);
            var clusters = denStream.Cluster();

            var clusterPoints = new List<dynamic>();
            foreach (var (i, cluster) in clusters.Enumerate())
            {
                foreach (var point in cluster)
                {
                    clusterPoints.Add(new {x = point.X, y = point.Y, c = i});
                }
            }

            Console.WriteLine($"Waiting...");
            Thread.Sleep(2000);
            Console.WriteLine($"Terminating MaintainClusterMap");
            terminate();

            return Ok(JsonConvert.SerializeObject(clusters));
        }
    }
}