version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore EnvueClustering/EnvueClustering.sln
      - run: dotnet build EnvueClustering/EnvueClustering.sln
      - run: dotnet test --no-build EnvueClustering/EnvueClustering.Tests

  integration_test:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore EnvueClustering/EnvueClustering.sln
      - run: dotnet build EnvueClustering/EnvueClusteringAPI/EnvueClusteringAPI.csproj
      - run: dotnet run --project EnvueClustering/EnvueClusteringAPI/
      - run: sleep 6
      - run: dotnet test --no-build EnvueClustering/EnvueClusteringAPI.Tests

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker build -t envue/clustering .
      - run: docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}
      - run: docker push envue/clustering

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - integration_test:
         requires:
           - build
         filters:
           branches:
             only: testing-integration
      - deploy:
         requires:
           - build
         filters:
           branches:
             only: master
