version: 2
jobs:
  test:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore EnvueClustering/EnvueClustering.sln
      - run: dotnet build EnvueClustering/EnvueClustering.sln
      - run: dotnet test --no-build EnvueClustering/EnvueClustering.Tests

  integration_test:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore EnvueClustering/EnvueClustering.sln
      - run: dotnet build EnvueClustering/EnvueClustering.sln
      - run: 
          name: Starting API
          command: dotnet run --project EnvueClustering/EnvueClusteringAPI/
          background: true
      - run: sleep 6
      - run: dotnet test --no-build EnvueClustering/EnvueClusteringAPI.Tests

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker build -t envue/clustering .
      - run: docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}
      - run: docker push envue/clustering

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - integration_test:
         requires:
           - test
         filters:
           branches:
             only:
               - testing-integration
               - master
      - deploy:
         requires:
           - integration_test
         filters:
           branches:
             only: master
