using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Newtonsoft.Json;

namespace EnvueClustering.Data
{
    /// <summary>
    /// Class responsible for handling the loading of continuously structured and evolving data streams.
    /// Understands a small set of predefined continuous data formats. 
    /// </summary>
    public static class ContinuousDataReader
    {
        /// <summary>
        /// Reads the data from a .synthetic file generated by the data generation Processing script.
        /// Returns a List((float[], int)). 
        /// </summary>
        /// <param name="filePath"></param>
        public static ConcurrentQueue<EuclideanPoint> ReadSyntheticEuclidean(string filePath)
        {
            var json = JsonConvert.DeserializeObject<IEnumerable<EuclideanPoint>>(File.ReadAllText(filePath));
            return new ConcurrentQueue<EuclideanPoint>(json);
        }
    }
}